### ISSUE TITLE
Team parser and main contest script

### ISSUE THREAD

**Issue by jsego** [jsego/pacman-eutopia#8]
The team JSON parser (commit: [3e2074d](https://github.com/jsego/pacman-eutopia/commit/3e2074d4a7bb65d5bbfed5d6fd30a6c4c65256a0)) can be used in the main contest script.

Next ToDo tasks (for each contest):
- [x] clone repositories that are locally missing (relates to Issue #2)
- [x] update all repositories and check which changed (relates to Issue #2)
- [x] prepare the "new vs all" (do not repeat "old vs old" games)
- [x] send the cluster calls for each pair of teams
- [x] retrieve results and update html (relates to Issue #4 and #11)

**Comment by jsego** [comment]
The scripts have been written as slurm array tasks in two steps.
First generate all commands, then send the slurm array tasks where each id corresponds to a match.
